apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "elasticsearch-security-operator.fullname" . }}-rolebinding
  labels:
    {{- include "elasticsearch-security-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "elasticsearch-security-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "elasticsearch-security-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
