{{- if .Values.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elasticsearch-security-operator.fullname" . }}-config
  labels:
{{- include "elasticsearch-security-operator.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: |
    {{ toYaml .Values.config | b64enc }}
{{- end }}
