{{- if .Values.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elasticsearch-security-operator.fullname" . }}-config
  labels:
{{- include "elasticsearch-security-operator.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: |
    {{ printf "endpoint: %v \nalertAPIPath: %v \nroleAPIPath: %v \nuserAPIPath: %v \nroleMappingAPIPath: %v \nextraCACertFile: %v \nusername: %v \npassword: %v \n" .Values.config.endpoint .Values.config.alertAPIPath .Values.config.roleAPIPath .Values.config.userAPIPath .Values.config.roleMappingAPIPath .Values.config.extraCACertFile .Values.config.username .Values.config.password | b64enc }}
{{- end }}
