apiVersion: security.rshbdev.ru/v1alpha1
kind: Role
metadata:
  name: role-sample
spec:
  cluster_permissions:
  - cluster_composite_ops
  - indices_monitor
  index_permissions:
  - index_patterns:
    - movies*
    dls: |-
      {"bool": {"must": {"match": {"kubernetes.cluster_name": "teststbl"}}}}
    fls: []
    masked_fields: []
    allowed_actions:
    - read
  tenant_permissions:
  - tenant_patterns:
    - human_resources
    allowed_actions:
    - kibana_all_read
  roleMappings:
    backend_roles:
      - test1
    users:
      - sample-user
